# Node.js
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - master
    - feat/*
    exclude:
    - wip/*

variables:
  azureSubscriptionEndpoint: julie-ng-connection
  azureContainerRegistry: julie.azurecr.io
  imageTag: $(azureContainerRegistry)/$(Build.Repository.Name):$(Build.BuildId)

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'npm install'

# Sometimes audit via npmjs.org unreliable…
- script: npm audit
  displayName: 'Dependency Audit'

- script: npm run lint
  displayName: 'Lint Code'

- script: npm run test
  displayName: 'Unit Tests'

# Use the task to avoid embedding credentials in pipeline
- task: Docker@1
  displayName: 'Docker: login ACR'
  inputs:
    command: login
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)

- script: docker build --tag  $(imageTag) .
  displayName: 'Docker: build and tag image'

- script: docker push $(imageTag)
  displayName: 'Docker: push image'

- script: docker logout $(azureContainerRegistry)
  displayName: 'Docker: logout ACR'
