# Node.js
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - master
    - feat/*
    exclude:
    - wip/*

variables:
  azureSubscriptionEndpoint: julie-ng-connection
  azureContainerRegistry: julie.azurecr.io
  imageTag: $(azureContainerRegistry)/$(Build.Repository.Name):$(Build.BuildId)

pool:
  vmImage: 'Ubuntu-16.04'

steps:
  - script: |
      '##vso[task.setvariable variable=buildSha]'$(git rev-parse --short HEAD)''
      echo 'Setting buildSha to $(buildSha)'
    displayName: set build sha var

  - bash: 'echo $(buildSha)'
    displayName: output sha var in another task