# Node.js
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

variables:
  azureSubscriptionEndpoint: julie-ng # Name of the Azure Service Connection
  azureContainerRegistry: julie.azurecr.io

trigger:
  branches:
    include:
    - master
    - feat/*
    exclude:
    - wip/*

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'npm install'

# Sometimes audit via npmjs.org unreliable…
- script: npm audit
  displayName: 'Dependency Audit'

- script: npm run lint
  displayName: 'Lint Code'

- script: npm run test
  displayName: 'Unit Tests'

- task: Docker@1
  displayName: Azure CR Login
  inputs:
    command: login
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)
