# Node.js
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - master
    - feat/*
    exclude:
    - wip/*

variables:
  azureSubscriptionEndpoint: julie-ng-connection 
  azureContainerRegistry: julie.azurecr.io
  
pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: Docker@1
  displayName: Container registry login
  inputs:
    command: login
    azureSubscriptionEndpoint: ${azureSubscriptionEndpoint}
    azureContainerRegistry: ${azureContainerRegistry}